-- MySQL Script generated by MySQL Workbench
-- Sun Jan 21 18:09:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema s3y
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema s3y
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s3y` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `s3y` ;

-- -----------------------------------------------------
-- Table `s3y`.`Employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`Employer` (
  `emp_id` BIGINT NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Phone_number` VARCHAR(45) NOT NULL,
  `img` LONGBLOB NULL DEFAULT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`emp_id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`employee` (
  `National_id` BIGINT NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Phone_number` VARCHAR(45) NOT NULL,
  `Personal_image` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `verified` BIGINT NOT NULL,
  PRIMARY KEY (`National_id`),
  UNIQUE INDEX `National_id_UNIQUE` (`National_id` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`Links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`Links` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Linkedin` VARCHAR(45) NULL DEFAULT NULL,
  `Github` VARCHAR(45) NULL DEFAULT NULL,
  `other` VARCHAR(45) NULL DEFAULT NULL,
  `employee_National_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `employee_National_id`),
  INDEX `fk_Links_employee1_idx` (`employee_National_id` ASC) VISIBLE,
  CONSTRAINT `fk_Links_employee1`
    FOREIGN KEY (`employee_National_id`)
    REFERENCES `s3y`.`employee` (`National_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`Payments` (
  `id` VARCHAR(45) NOT NULL,
  `status` BIGINT NOT NULL,
  `Total_amount` BIGINT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`category` (
  `name` VARCHAR(20) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`reviews` (
  `id` BIGINT NOT NULL,
  `text` VARCHAR(200) NOT NULL,
  `img` LONGBLOB NULL DEFAULT NULL,
  `rating` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`Tasks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Descr` VARCHAR(200) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `posting_date` DATETIME NOT NULL,
  `deadline` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `img` LONGBLOB NULL DEFAULT NULL,
  `note` VARCHAR(100) NULL DEFAULT NULL,
  `Employer_emp_id` BIGINT NOT NULL,
  `category_id` VARCHAR(45) NOT NULL,
  `Payments_id` VARCHAR(45) NOT NULL,
  `reviews_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `Employer_emp_id`, `category_id`, `Payments_id`, `reviews_id`),
  INDEX `fk_Tasks_Employer1_idx` (`Employer_emp_id` ASC) VISIBLE,
  INDEX `fk_Tasks_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_Tasks_Payments1_idx` (`Payments_id` ASC) VISIBLE,
  INDEX `fk_Tasks_reviews1_idx` (`reviews_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tasks_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `s3y`.`category` (`id`),
  CONSTRAINT `fk_Tasks_Employer1`
    FOREIGN KEY (`Employer_emp_id`)
    REFERENCES `s3y`.`Employer` (`emp_id`),
  CONSTRAINT `fk_Tasks_Payments1`
    FOREIGN KEY (`Payments_id`)
    REFERENCES `s3y`.`Payments` (`id`),
  CONSTRAINT `fk_Tasks_reviews1`
    FOREIGN KEY (`reviews_id`)
    REFERENCES `s3y`.`reviews` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`Tasks_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`Tasks_has_employee` (
  `Tasks_id` BIGINT NOT NULL,
  `employee_National_id` BIGINT NOT NULL,
  PRIMARY KEY (`Tasks_id`, `employee_National_id`),
  INDEX `fk_Tasks_has_employee_employee1_idx` (`employee_National_id` ASC) VISIBLE,
  INDEX `fk_Tasks_has_employee_Tasks_idx` (`Tasks_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tasks_has_employee_employee1`
    FOREIGN KEY (`employee_National_id`)
    REFERENCES `s3y`.`employee` (`National_id`),
  CONSTRAINT `fk_Tasks_has_employee_Tasks`
    FOREIGN KEY (`Tasks_id`)
    REFERENCES `s3y`.`Tasks` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`certficates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`certficates` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `employee_National_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `employee_National_id`),
  INDEX `fk_certficates_employee1_idx` (`employee_National_id` ASC) VISIBLE,
  CONSTRAINT `fk_certficates_employee1`
    FOREIGN KEY (`employee_National_id`)
    REFERENCES `s3y`.`employee` (`National_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`employee_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`employee_has_category` (
  `employee_National_id` BIGINT NOT NULL,
  `category_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_National_id`, `category_id`),
  INDEX `fk_employee_has_category_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_employee_has_category_employee1_idx` (`employee_National_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `s3y`.`category` (`id`),
  CONSTRAINT `fk_employee_has_category_employee1`
    FOREIGN KEY (`employee_National_id`)
    REFERENCES `s3y`.`employee` (`National_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`messages` (
  `id` BIGINT NOT NULL,
  `text` VARCHAR(1000) NOT NULL,
  `img` LONGBLOB NULL DEFAULT NULL,
  `Date` DATETIME NOT NULL,
  `employee_National_id` BIGINT NOT NULL,
  `Employer_emp_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `employee_National_id`, `Employer_emp_id`),
  INDEX `fk_messages_employee1_idx` (`employee_National_id` ASC) VISIBLE,
  INDEX `fk_messages_Employer1_idx` (`Employer_emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_employee1`
    FOREIGN KEY (`employee_National_id`)
    REFERENCES `s3y`.`employee` (`National_id`),
  CONSTRAINT `fk_messages_Employer1`
    FOREIGN KEY (`Employer_emp_id`)
    REFERENCES `s3y`.`Employer` (`emp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s3y`.`problems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s3y`.`problems` (
  `id` BIGINT NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `img` LONGBLOB NOT NULL,
  `Employer_emp_id` BIGINT NOT NULL,
  `employee_National_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `Employer_emp_id`, `employee_National_id`),
  INDEX `fk_problems_Employer1_idx` (`Employer_emp_id` ASC) VISIBLE,
  INDEX `fk_problems_employee1_idx` (`employee_National_id` ASC) VISIBLE,
  CONSTRAINT `fk_problems_employee1`
    FOREIGN KEY (`employee_National_id`)
    REFERENCES `s3y`.`employee` (`National_id`),
  CONSTRAINT `fk_problems_Employer1`
    FOREIGN KEY (`Employer_emp_id`)
    REFERENCES `s3y`.`Employer` (`emp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
